### ISSUE TITLE
add image alt tag as a property to the Image Options

### ISSUE THREAD

**Issue by VidiHawk** [OriAmir/React-Responsive-Gallery#19] opened 2022-06-06 16:33 UTC
Well done OriAmir for this great gallery. I love it!

It would be great to have an additional property in Image Options to declare the alt tags for each image. 
alt tags are really important for SEO nowadays.

**Comment by OriAmir** [comment] 2022-06-08 14:11
Hi @VidiHawk thanks the for the warm words.

Relate to the alt Tag- great idea, I will add that soon.

**Comment by VidiHawk** [comment] 2022-06-09 06:09
Thank you @OriAmir . 

I also noticed an error in the browser. Not sure if you are getting it too. I created a simple webpage displaying 4 galleries. They are all displaying and behaving as expected (well done on the responsive part by the way. It works like a charm!). But I am still getting these error in the console. It seems that the width is not being passed to the browser. I assume this kind of error can also affect ranking on search engines. See bellow screenshot:


![image](https://user-images.githubusercontent.com/106433016/172776190-aa26a92f-a67d-4bfa-8072-214f4a54d230.png)

**Comment by OriAmir** [comment] 2022-06-09 16:08
@VidiHawk many thanks for that also! could you provide me pls:
Browser 
Browser version
React version
SSR/CSR/else
Snippet of the code you are using

Thanks a lot, it's will really help me to find that and try to solve that asap.

**Comment by VidiHawk** [comment] 2022-06-10 11:23
Hi @OriAmir, sure:

Firefox Version 101.0
Chrome Version 102.0.5005.63
react: "^18.1.0"
CSR with create-react-app

Here is the code:
```
import React from "react";
import ResponsiveGallery from "react-responsive-gallery";
import { images } from "../helpers/Import";

const g1 = [
  { src: images["1.jpg"] },
  { src: images["2.jpg"] },
  { src: images["3.jpg"] },
  { src: images["4.jpg"] },
];

const g2 = [
  { src: images["5"] },
  { src: images["6"] },
  { src: images["7"] },
  { src: images["8"] },
];

export class ResponsiveContent extends React.Component {
  render() {
    return [
      <ResponsiveGallery
        key="01"
        images={g1}
        numOfImagesPerRow={{ xs: 1, s: 2, m: 2, l: 4, xl: 4, xxl: 4 }}
      />,
      <br></br>,
      <ResponsiveGallery
        key="02"
        images={g2}
        numOfImagesPerRow={{ xs: 1, s: 2, m: 2, l: 4, xl: 4, xxl: 4 }}
      />,
    ];
  }
}

```

**Comment by OriAmir** [comment] 2022-06-11 11:29
hi @VidiHawk ,thanks for the information.
I tried locally to run your snippet and I can't reproduce this warning.
I working with macOS Monterey and I've tried on Safari, Chrome, and Firefox browsers with 2 versions of the component - class and function.
I also tried on `stackblitz` and cant reproduce that, can you take a look here and tell me how you got the warning?
https://stackblitz.com/edit/rrs-test?file=App.tsx

many thanks.

**Comment by VidiHawk** [comment] 2022-06-11 13:19
I am not experiencing warning with your code on `stackblitz` either.
Not sure what it is. I am busy over the week end but will try to look into it next week.

**Comment by OriAmir** [comment] 2022-06-21 21:46
hi @VidiHawk , I just publish a new version (2.1.2) with the alt option to the image, thanks for the comment.

I close this issue, if you will succeed to reproduce the warning you described above please open a new ticket, thanks!

**Closed as completed by OriAmir** 2022-06-21 21:46 UTC

**Comment by VidiHawk** [comment] 2022-06-22 06:13
Thanks @OriAmir , I tested your new release and it works like a charm. Regarding the above mentioned warning, I managed to solve it and it is not related to your code. Thanks for looking into this!

**Comment by OriAmir** [comment] 2022-06-22 16:02
great, thanks for the feedback, it's really helpful!
